linters-settings:
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: server_test\.go
      linters:
        - paralleltest
        - tparallel
      text: TestServer_Start

    - path: server_test\.go
      linters:
        - bodyclose
