name: CI
on:
  pull_request:
    types: [opened, synchronize] # these are the defaults - synchronize means 'commits pushed to PR'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests and race detection
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
        id: go

      - name: Check out code
        uses: actions/checkout@v5

      - name: Get dependencies
        shell: bash
        run: go get -v -t -d ./...

      - name: Run tests with race detection
        run: go test -v -race ./...

      - name: Run build
        run: go build

  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
